# Generated by Django 2.1 on 2019-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_auto_20190928_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='h_account',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
