# Generated by Django 2.2.6 on 2019-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_auto_20191002_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='context',
            field=models.TextField(),
        ),
    ]
