# Generated by Django 2.2.6 on 2019-10-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0008_auto_20191016_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='company',
            field=models.CharField(max_length=55, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='title',
            field=models.CharField(max_length=20, verbose_name='标题'),
        ),
    ]
