# Generated by Django 2.2.6 on 2019-10-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0009_auto_20191016_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='hr',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='recruiting.Hr'),
            preserve_default=False,
        ),
    ]
