# Generated by Django 2.2.6 on 2019-10-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0011_auto_20191021_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='skill',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='a_account',
            field=models.CharField(max_length=20, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=11, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sex',
            field=models.PositiveIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='statue',
            field=models.PositiveIntegerField(choices=[(1, '未登录'), (2, '已登录')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
    ]
