# Generated by Django 2.2.6 on 2019-10-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0012_auto_20191021_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='sex',
            field=models.PositiveIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
    ]
