# Generated by Django 2.2.6 on 2019-10-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0013_auto_20191021_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='username',
            field=models.CharField(default=11, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Hr', verbose_name='发布人'),
        ),
    ]
